//
//  Video.swift
//  Mathtivity
//
//  Created by Andrew Tran on 11/25/18.
//  Copyright © 2018 Andrew Tran. All rights reserved.
//

import Foundation
import UIKit
class Video {
    var videoTitle = ""
    var videoURL = ""
    
    init(videoTitle: String, videoURL: String) {
        self.videoTitle = videoTitle
        self.videoURL = videoURL
    }
    static func fetchCryptographyVideos() -> [Video] {
        return [
            Video(videoTitle: "1 - Course Overview", videoURL: "XZilNNuw-Eg"),
            Video(videoTitle: "2 - What is Cryptography?", videoURL: "h0GYdrDVQko"),
            Video(videoTitle: "3 - History of Cryptography", videoURL: "yu90EU-4xAY"),
            Video(videoTitle: "4 - Discrete Probability", videoURL: "AEL69H2HbPY"),
            Video(videoTitle: "5 - Discrete Probability pt.2", videoURL: "a1SKO0RF3Uk"),
            Video(videoTitle: "6 - Info Theoretic Security & One Time Pad", videoURL: "dCa0Fe12PIQ"),
            Video(videoTitle: "7 - Stream Cipher & Psuedo Random Generators", videoURL: "Kh8OJERWgbM"),
            Video(videoTitle: "8 - Attacks on Stream Ciphers & One Time Pad", videoURL: "19EY-sr0PNc"),
            Video(videoTitle: "9 - Real World Stream Ciphers", videoURL: "ytjA3xGOKsU"),
            Video(videoTitle: "10 - PRG Security Definitions", videoURL: "gFrJHXpssHo"),
            Video(videoTitle: "11 - Semantic Security", videoURL: "eomGldrNr88"),
            Video(videoTitle: "12 - Stream Ciphers are Semantically Secure", videoURL: "f6Dt_0m-nbI"),
            Video(videoTitle: "13 - What are Block Ciphers?", videoURL: "a28mKx9K8H4"),
            Video(videoTitle: "14 - The Data Encryption Standard", videoURL: "fcjadxYY9G0"),
            Video(videoTitle: "15 - Exhaustive Search Attacks", videoURL: "wtpxNsKCS20"),
            Video(videoTitle: "16 - More Attacks on Block Ciphers", videoURL: "XEu333sBKTY"),
            Video(videoTitle: "17 - The AES Block Cipher", videoURL: "XKCiVdOEvmU"),
            Video(videoTitle: "18 - Block Ciphers From PRGs", videoURL: "1Vtq7IQcHYQ"),
            Video(videoTitle: "19 - Review PRPs and PRFs", videoURL: "YchrmlHUWz8"),
            Video(videoTitle: "20 - Modes of Operation one time Key", videoURL: "OnBNYGGPK_Y"),
            Video(videoTitle: "21 - Security For Many Time Key", videoURL: "si4dM6TR_MU"),
            Video(videoTitle: "22 - Modes of Operation Many Time Key CBC", videoURL: "gbNkAiLYOBE"),
            Video(videoTitle: "23 - Modes of Operation Many Time Key CTR", videoURL: "9i8UL6lXqpg"),
            Video(videoTitle: "24 - Message Authentication Codes", videoURL: "VJMCbMQCrhI"),
            Video(videoTitle: "25 - MACs Based on PRFs", videoURL: "rnA9ar3CDVY"),
            Video(videoTitle: "26 - CBC MAC and NMAC", videoURL: "8ykCKHGf400"),
            Video(videoTitle: "27 - MAC Padding", videoURL: "_ufVwtIuvUY"),
            Video(videoTitle: "28 - PMAC and the Carter Wegman MAC", videoURL: "kYJtrW_MSfU"),
            Video(videoTitle: "29 - Intro to Collision Resistance", videoURL: "0j2Kam7QFWc"),
            Video(videoTitle: "30 - Generic Birthday Attack", videoURL: "XtJTCgD1ohg"),
            Video(videoTitle: "31 - The Merkle Damgard Paradigm", videoURL: "s9S6XRUmpLY"),
            Video(videoTitle: "32 - Constructing Compression Functions", videoURL: "CapbYFNxngE"),
            Video(videoTitle: "33 - HMAC", videoURL: "3KFYCg7qWfU"),
            Video(videoTitle: "34 - Timing attacks on MAC verification", videoURL: "b9eobfui-aQ"),
            Video(videoTitle: "35 - Active attacks on CPA secure encryption", videoURL: "lXyiK4hhH-Q"),
            Video(videoTitle: "36 - Definitions", videoURL: "Zh_b6guQiJg"),
            Video(videoTitle: "37 - Chosen ciphertext attacks", videoURL: "AOPUVd-P13U"),
            Video(videoTitle: "38 - Constructions from Ciphers & MACs", videoURL: "i4AdQDizWCI"),
            Video(videoTitle: "39 - Case Study TLS", videoURL: "BpzOlq1jgks"),
            Video(videoTitle: "40 - CBC Padding Attacks", videoURL: "3bL18vY-3Vs"),
            Video(videoTitle: "41 - Attacking non atomic decryption", videoURL: "a26LVpJgljA"),
            Video(videoTitle: "42 - Key Derivation", videoURL: "iic8FbKuvFg"),
            Video(videoTitle: "43 - Deterministic Encryption", videoURL: "likE6YD9w7Y"),
            Video(videoTitle: "44 - Deterministic EncryptionSIV and Wide PRP", videoURL: "bpC_k_xcTH8"),
            Video(videoTitle: "45 - Tweakable Encryption", videoURL: "-VUGVLgbFLs"),
            Video(videoTitle: "46 - Format Preserving Encryption", videoURL: "LjacONQMO1s"),
            Video(videoTitle: "47 - Trusted 3rd Parties", videoURL: "1x4BUIDvPHo"),
            Video(videoTitle: "48 - Merkle Puzzles", videoURL: "UmwqAx1i_GE"),
            Video(videoTitle: "49 - The Diffie Hellman Protocol", videoURL: "QHw9RVYuBTo"),
            Video(videoTitle: "50 - Public Key Encryption", videoURL: "aoMQlVFkIyc"),
            Video(videoTitle: "51 - Notation", videoURL: "O3OBgvhfuxI"),
            Video(videoTitle: "52 - Fermat & Euler", videoURL: "tleD818mneU"),
            Video(videoTitle: "53 - Modular Eth Roots", videoURL: "vVsHlc71lsg"),
            Video(videoTitle: "54 - Arithmetic Algorithms", videoURL: "XIvyvzAGoJc"),
            Video(videoTitle: "55 - Intractable Problems", videoURL: "zHnMIafV9mc"),
            Video(videoTitle: "56 - Definitions & Security", videoURL: "Y3mut4WlHFE"),
            Video(videoTitle: "57 - Constructions", videoURL: "xSPQrPZ2G9w"),
            Video(videoTitle: "58 - The RSA Trapdoor Functions", videoURL: "ssYa7XH2Kjc"),
            Video(videoTitle: "59 - PKCS 1", videoURL: "F-sfHYG9ZO0"),
            Video(videoTitle: "60 - Is RSA a one way function?", videoURL: "sT04_eUMAbs"),
            Video(videoTitle: "61 - RSA in Practice", videoURL: "Art8WQpIXZk"),
            Video(videoTitle: "62 - The EIGamal Public Key System", videoURL: "bnZ2D43uCcs"),
            Video(videoTitle: "63 - EIGamal Security", videoURL: "ZNNGsHjrG9M"),
            Video(videoTitle: "64 - EIGamal Variants With Better Security", videoURL: "Ko4alB9Cnc8"),
            Video(videoTitle: "65 - A Unifying Theme", videoURL: "hyB-2ANTdvk"),
            Video(videoTitle: "66 - Farewell for now", videoURL: "nUwpSGgNRCM")
        ]
    }
    static func fetchImaginaryVideos() -> [Video] {
        return [
            Video(videoTitle: "A message from Andrew!", videoURL: "xEIHZ8c5lzA"),
            Video(videoTitle: "1 - Introduction", videoURL: "T647CGsuOVU"),
            Video(videoTitle: "2 - A Little History", videoURL: "2HrSG0fdxLY"),
            Video(videoTitle: "3 - Cardan's Problem", videoURL: "N9QOLrfcKNc"),
            Video(videoTitle: "4 - Bombelli's Solution", videoURL: "DThAoT3q2V4"),
            Video(videoTitle: "5 - Numbers are Two Dimensional", videoURL: "65wYmy8Pf-Y"),
            Video(videoTitle: "6 - The Complex Plane", videoURL: "z5IG_6_zPDo"),
            Video(videoTitle: "7 - Complex Multiplication", videoURL: "YHvR8siIiD0"),
            Video(videoTitle: "8 - Math Wizardry", videoURL: "iecUL8_OxrU"),
            Video(videoTitle: "9 - Closure", videoURL: "dLn5H69lS0w"),
            Video(videoTitle: "10 - Complex Functions", videoURL: "pNp8Qf20-sA"),
            Video(videoTitle: "11 - Wandering in 4 Dimensions", videoURL: "0hiWbdc8QEk"),
            Video(videoTitle: "12 - Reimann's Solution", videoURL: "DpUmrKOQhAM"),
            Video(videoTitle: "13 - Reimann's Surfaces", videoURL: "4MmSZrAlqKc")
        ]
    }
    static func fetchProofVideos() -> [Video] {
        return [

            Video(videoTitle: "1 - Proof that 1 = 0; patrickJMT", videoURL: "4ZpUjcLJEqw"),
            Video(videoTitle: "2 - Proof 1 = 2; John Hush", videoURL: "hI9CaQD7P6I"),
            Video(videoTitle: "3 - The Pythagoras Proof", videoURL: "FS7qEDJys_Q"),
            Video(videoTitle: "4 - Why 1/0 is undefined", videoURL: "jhxm7GSbGgg"),
            Video(videoTitle: "5 - Square Root of 2", videoURL: "CmKXE9vvubY"),
            Video(videoTitle: "6 - Proof π is IRRATIONAL; Mathologer", videoURL: "Lk_QF_hcM8A"),
            Video(videoTitle: "7 - Can we make sense of irrationality?", videoURL: "Fks6Z9m8D-E"),
            Video(videoTitle: "8 - Proof e is irrational; MindYourDecisions", videoURL: "CZ0pELTBsRQ"),
            Video(videoTitle: "9 - Where does πr(squared) come from?; mathematicsonline", videoURL: "YokKp3pwVFc"),
            Video(videoTitle: "10 - How can we derive the volume of a sphere?; mathematicsonline", videoURL: "xuPl_8o_j7k"),
            Video(videoTitle: "11 - Why isn't 1 a prime number?; Numberphile", videoURL: "IQofiPqhJ_s"),
            Video(videoTitle: "12 - Negative Numbers Make No Sense", videoURL: "JK_7JuE6y1E"),
            Video(videoTitle: "13 - Are all triangles 180 degrees?", videoURL: "JKRP2IjWjrM")
        ]
    }
    static func fetchRRVideos() -> [Video] {
        return [
            Video(videoTitle: "1 - Course Introduction", videoURL: "pu20MKRz16o"),
            Video(videoTitle: "2 - Rocketry History", videoURL: "o5uxtuPChtI"),
            Video(videoTitle: "3 - Non Reusable Systems", videoURL: "tAEYvHPFvk8"),
            Video(videoTitle: "4 - Reusable Systems", videoURL: "76e6FtlLD3s"),
            Video(videoTitle: "5 - SpaceX Overview", videoURL: "eg-0JsEhIsI"),
            Video(videoTitle: "6 - How SpaceX Engines Work", videoURL: "uPAJsjbMN3I"),
            Video(videoTitle: "7 - SpaceX Logistics", videoURL: "hjDaEX2qN74"),
            Video(videoTitle: "8 - The Future of Aerospace", videoURL: "miEz1SsnkO0"),
            Video(videoTitle: "9 - Course Conclusion", videoURL: "wRzDMx6YBLw")
        ]
    }
    static func fetchHistoryVideos() -> [Video] {
        return [
            Video(videoTitle: "General Overview & Dev. of Numbers", videoURL: "pk49iM9OT_0"),
            Video(videoTitle: "Golden Ratio & Fibbonacci Numbers", videoURL: "4oyyXC5IzEE"),
            Video(videoTitle: "The Birth of Algebra", videoURL: "FME9avU3u2Y"),
            Video(videoTitle: "Calculus: One of the Most successful Technologies", videoURL: "8ZLC0egL6pc"),
            Video(videoTitle: "How did Humans Acquire Math Abilities?", videoURL: "NnVubBrATIU")
        ]
    }
    static func fetchWeirdVideos() -> [Video] {
        return [
            Video(videoTitle: "Numberphile: 1+2+3+4..= (-1/12)???", videoURL: "w-I6XTVZXww"),
            Video(videoTitle: "Numberphile: One plus one minus one...", videoURL: "PCu_BNNI5x4"),
            Video(videoTitle: "Numberphile: Why -1/12 is a gold nugget", videoURL: "0Oazb7IWzbA"),
            Video(videoTitle: "Numberphile: The REIMANN Hypothesis?", videoURL: "d6c6uIyieoo"),
            Video(videoTitle: "Numberphile: Problems with 0...", videoURL: "BRRolKTlF6Q"),
            Video(videoTitle: "Numberphile: What is Graham's Number?", videoURL: "HX8bihEe3nA"),
            Video(videoTitle: "Numberphile: How big is Graham's Number?", videoURL: "GuigptwlVHo"),
            Video(videoTitle: "Numberphile: The Enormous TREE(3)", videoURL: "3P6DWAwwViU"),
            Video(videoTitle: "Numberphile2: More on TREE(3)", videoURL: "IihcNa9YAPk"),
            Video(videoTitle: "Numberphile: How many Particles?", videoURL: "lpj0E0a0mlU"),
            Video(videoTitle: "MAA: Does 0.9999.. = 1?", videoURL: "x-fUDqXlmHM"),
            Video(videoTitle: "MAA: Magical Squaring", videoURL: "_FoONg5Meyc"),
            Video(videoTitle: "Standupmaths: What is i^i?", videoURL: "9tlHQOKMHGA"),
            Video(videoTitle: "Standupmaths: There is only one Parabola", videoURL: "hoh4TmPzu1w"),
            Video(videoTitle: "Standupmaths: Calculating π by Hand", videoURL: "HrRMnzANHHs"),
            Video(videoTitle: "Eddie Woo: Why is 0! = 1?", videoURL: "X32dce7_D48"),
            Video(videoTitle: "Eddie Woo: What is 0^0?", videoURL: "r0_mi8ngNnM"),
            Video(videoTitle: "Eddie Woo: Dividing by Zero?", videoURL: "J2z5uzqxJNU"),
            Video(videoTitle: "Eddie Woo: Think Deeply About Simple Things", videoURL: "-YJSDJGyIaU"),
            Video(videoTitle: "Eddie Woo: Proof (2^n) ≥ (n^2)", videoURL: "cXNdy-HHqrA"),
            Video(videoTitle: "Veritasium: Can you Solve This?", videoURL: "vKA4w2O61Xo"),
            Video(videoTitle: "Veritasium: The Bayesian Trap", videoURL: "R13BD8qKeTg"),
            Video(videoTitle: "Veritasium: This Breaks Time Symmetry", videoURL: "yArprk0q9eE"),
            Video(videoTitle: "Veritasium: What is NOT Random?", videoURL: "sMb00lz-IfE"),
            Video(videoTitle: "Veritasium: Faster Than Light?", videoURL: "EPsG8td7C5k"),
            Video(videoTitle: "Vsauce: The Banach-Tarski Paradox", videoURL: "s86-Z-CbaHA"),
            Video(videoTitle: "Vsauce: Count Past Infinity", videoURL: "SrU9YDoXE88"),
            Video(videoTitle: "3Blue1Brown: The most Beautiful Equation", videoURL: "F_0yfvm0UoU")
        ]
    }
    static func fetchSATVideos() -> [Video] {
        return [
            Video(videoTitle: "SAT Math Course Intro", videoURL: "f626i-9QYNo"),
            Video(videoTitle: "1 - Do trig without knowing trig", videoURL: "KIORXepRfXA"),
            Video(videoTitle: "2 - Working With Scatterplots", videoURL: "A9B_5qmtK-Y"),
            Video(videoTitle: "3 - Cross Out Unimportant Things", videoURL: "xLHjMMDt-Co"),
            Video(videoTitle: "4 - Interpreting Non Linear Equations", videoURL: "X2BqxbiXlOw"),
            Video(videoTitle: "5 - Take Your Time!", videoURL: "q4Q50HgHbKA"),
            Video(videoTitle: "6 - Solving For Angles", videoURL: "duuYLBJuY50"),
            Video(videoTitle: "7 - Substitution SOE", videoURL: "UwmFcoLUu-k"),
            Video(videoTitle: "8 - Elimination SOE", videoURL: "sGHL3nUb4rE"),
            Video(videoTitle: "9 - Working With Units", videoURL: "jeYKzay2H6M"),
            Video(videoTitle: "10 - Start with what you know", videoURL: "OYZIoSD1l94"),
            Video(videoTitle: "11 - Analyzing Word Problems", videoURL: "Ocm4Pv8htoY"),
            Video(videoTitle: "12 - 1 Info Set, 2 Questions", videoURL: "T-FQM8B6Azg"),
            Video(videoTitle: "13 - Interpreting Word Problems", videoURL: "RgpvZmN2MKA"),
            Video(videoTitle: "14 - Circle Equation", videoURL: "w0RazKZ8Peg"),
            Video(videoTitle: "15 - Analyzing Graphs", videoURL: "TfBQkzCCFUI"),
            Video(videoTitle: "16 - Don't be Afraid of the Problem", videoURL: "9LDatqavbdY"),
            Video(videoTitle: "17 - Equivalent Expressions", videoURL: "5qLf_iR6Fv0"),
            Video(videoTitle: "18 - The Best Guessing Trick", videoURL: "1pRqrNHXPX4"),
            Video(videoTitle: "19 - Exponent Manipulation", videoURL: "vx_ZMLB0IOw"),
            Video(videoTitle: "20 - Geometry Word Problems", videoURL: "DZLk5StxtTw"),
            Video(videoTitle: "21 - Interpreting Linear Equations", videoURL: "YsZ9A4lie2A"),
            Video(videoTitle: "22 - More Graph Analysis", videoURL: "gEQak2QNYgM"),
            Video(videoTitle: "23 - Common SAT Question #1", videoURL: "6RwhmF2EFs8"),
            Video(videoTitle: "24 - Common SAT Question #2", videoURL: "On3tMTFshJY"),
            Video(videoTitle: "25 - Common SAT Question #3", videoURL: "s8wWmOa6_aQ"),
            Video(videoTitle: "26 - Common SAT Question #4", videoURL: "jnRRvtjbatE"),
            Video(videoTitle: "27 - Common SAT Question #5", videoURL: "JudF_w_3IYs"),
            Video(videoTitle: "Course Conclusion", videoURL: "GIljWIh5vTc")
        ]
    }
    static func fetchMathStrategiesVideos() -> [Video] {
        return [
            Video(videoTitle: "1 - Engage in Successful Flailing", videoURL: "zkY4M3a022Q"),
            Video(videoTitle: "2 - Do Something!", videoURL: "1a8FKFk12jI"),
            Video(videoTitle: "3 - Eliminate Incorrect Answers", videoURL: "PXO7nPil5sM"),
            Video(videoTitle: "4 - Engage in Wishful Thinking...?", videoURL: "3AWX_X3zUao"),
            Video(videoTitle: "5 - Go to Extremes!", videoURL: "c3hhj4E99_w"),
            Video(videoTitle: "6 - Cut up the Shape!", videoURL: "rFaD9ZIoeA8"),
            Video(videoTitle: "7 - Simplify down to prime number", videoURL: "F3mA2cw_CgM"),
            Video(videoTitle: "8 - Store the value into \"a\"!", videoURL: "j7JBaXg2t58"),
            Video(videoTitle: "9 - Find any factor of 3", videoURL: "uaOZBkFgrMw"),
            Video(videoTitle: "10 - The units digit trick", videoURL: "-CsAcrOpIcU"),
            Video(videoTitle: "11 - Scale The Problem Down", videoURL: "HfN2q4UtECQ"),
            Video(videoTitle: "12 - Start With What You Know", videoURL: "Sj4ljgosskM"),
            Video(videoTitle: "13 - Visualize the Problem", videoURL: "zS0c7nBpEwY")
            
        ]
    }
    static func fetchJavaVideos() -> [Video] {
        return [
            Video(videoTitle: "1 - Installing the JDK", videoURL: "Hl-zzrqQoSE"),
            Video(videoTitle: "2 - Running a Java Program", videoURL: "5u8rFbpdvds"),
            Video(videoTitle: "3 - Downloading Eclipse", videoURL: "CE8UIbb_4iM"),
            Video(videoTitle: "4 - Hello World", videoURL: "SHIT5VkNrCg"),
            Video(videoTitle: "5 - Variables", videoURL: "gtQJXzi3Yns"),
            Video(videoTitle: "6 - Getting User Input", videoURL: "5DdacOkrTgo"),
            Video(videoTitle: "7 - Building a Basic Calculator", videoURL: "ANuuSFY2BbY"),
            Video(videoTitle: "8 - Math Operators", videoURL: "8ZaTSedtf9M"),
            Video(videoTitle: "9 - Increment Operators", videoURL: "ydcTx6idTs0"),
            Video(videoTitle: "10 - If Statement", videoURL: "iMeaovDbgkQ"),
            Video(videoTitle: "11 - Logical Operators", videoURL: "PAaqgTr7Cx4"),
            Video(videoTitle: "12 - Switch Statement", videoURL: "RVRPmeccFT0"),
            Video(videoTitle: "13 - While Loop", videoURL: "8ZuWD2CBjgs"),
            Video(videoTitle: "14 - Using Multiple Classes", videoURL: "XqTg2buXS5o"),
            Video(videoTitle: "15 - Methods With Parameters", videoURL: "7MBgaF8wXls"),
            Video(videoTitle: "16 - Many Methods & Instances", videoURL: "9t78g0U8VyQ"),
            Video(videoTitle: "17 - Constructors", videoURL: "tPFuVRbUTwA"),
            Video(videoTitle: "18 - Nested If-Statements", videoURL: "Y4xFGCyt1ww"),
            Video(videoTitle: "19 - Else-If Statements", videoURL: "C0YRYVn_BeI"),
            Video(videoTitle: "20 - Conditional Operators", videoURL: "Y6NheSwTsDs"),
            Video(videoTitle: "21 - Simple Averaging Problem", videoURL: "KXuQQh6AynQ"),
            Video(videoTitle: "22 - For Loops", videoURL: "rjkYAs6gAkk"),
            Video(videoTitle: "23 - Compound Interest Program", videoURL: "T9TcAm9g0mo"),
            Video(videoTitle: "24 - Do-While Loops", videoURL: "nfr52iR0Pyg"),
            Video(videoTitle: "25 - Math Class Methods", videoURL: "JzMdepMLW44"),
            Video(videoTitle: "26 - Random Number Generator", videoURL: "AhwIYAXPASw"),
            Video(videoTitle: "27 - Intro to Arrays", videoURL: "L06uGnF4IpY"),
            Video(videoTitle: "28 - Creating an Array Table", videoURL: "nTF-RcgsV0E"),
            Video(videoTitle: "29 - Summing Elements of Arrays", videoURL: "etyrkipdKvc"),
            Video(videoTitle: "30 - Array Elements as Counters", videoURL: "pHxtKDENDdE"),
            Video(videoTitle: "31 - Enhanced For Loop", videoURL: "w41D0V-BnKQ"),
            Video(videoTitle: "32 - Arrays in Methods", videoURL: "rzXoz2KOP7E"),
            Video(videoTitle: "33 - Multidimensional Arrays", videoURL: "ctab5xPv-Vk"),
            Video(videoTitle: "34 - Table for multi arrays", videoURL: "hbot9MQVHOM"),
            Video(videoTitle: "35 - Variable Length Arguements", videoURL: "BFL1oWnEO2k"),
            Video(videoTitle: "36 - Time Class", videoURL: "o4Or0PMI_aI"),
            Video(videoTitle: "37 - Display Regular Time", videoURL: "E0BTAqIltFc"),
            Video(videoTitle: "38 - Public, Private, & This", videoURL: "csjfLTt6-io"),
            Video(videoTitle: "39 - Multiple Class Constructors", videoURL: "LS7BzkBzn3Y"),
            Video(videoTitle: "40 - Set & Get Methods", videoURL: "eqP5X6APc5w"),
            Video(videoTitle: "41 - Building Objects For Constructors", videoURL: "MK2SMJZbUmU"),
            Video(videoTitle: "42 - toString()", videoURL: "l0N6WvIVoUI"),
            Video(videoTitle: "43 - Composition", videoURL: "ZBkyPA6NZR8"),
            Video(videoTitle: "44 - Enumeration", videoURL: "uFGrL5vyp54"),
            Video(videoTitle: "45 - EnumSet Range", videoURL: "r-_6fJpC-pk"),
            Video(videoTitle: "46 - Static", videoURL: "Mhxp5dZOy78"),
            Video(videoTitle: "47 - More on Static", videoURL: "14c1oJjgC8g"),
            Video(videoTitle: "48 - Final", videoURL: "Suxdg95FV1w"),
            Video(videoTitle: "49 - Inheritance", videoURL: "9JpNY-XAseg"),
            Video(videoTitle: "50 - Graphical UI; Interface GUI", videoURL: "jJjg4JweJZU"),
            Video(videoTitle: "51 - GUI w/ JFrame", videoURL: "jUdIAgJ7JKo"),
            Video(videoTitle: "52 - Event Handling", videoURL: "3EE7E3bvfe8"),
            Video(videoTitle: "53 - ActionListener", videoURL: "qhYook53olE"),
            Video(videoTitle: "54 - Event Handler Program", videoURL: "M1_-sigEPtE"),
            Video(videoTitle: "55 - Intro Polymorphism", videoURL: "0xw06loTm1k"),
            Video(videoTitle: "56 - Polymorphic Arguements", videoURL: "KKbN5pjBZGM"),
            Video(videoTitle: "57 - Overriding Rules", videoURL: "zN9pKULyoj4"),
            Video(videoTitle: "58 - Abstract & Concrete Classes", videoURL: "TyPNvt6Zg8c"),
            Video(videoTitle: "59 - Class to Hold Objects", videoURL: "slY5Ag7IjM0"),
            Video(videoTitle: "60 - Array Holding Many Objects", videoURL: "0--h2x6HENA"),
            Video(videoTitle: "61 - Simple Polymorphic Program", videoURL: "6d0m_L8_1XU"),
            Video(videoTitle: "62 - JButton", videoURL: "6iV-v_m0z0w"),
            Video(videoTitle: "63 - JButton Final Program", videoURL: "3RQOikbGGUM"),
            Video(videoTitle: "64 - JCheckBox", videoURL: "_UuDuj-RNRg"),
            Video(videoTitle: "65 - Final Checkbox Program", videoURL: "hyB-Y8zKDsenQFA"),
            Video(videoTitle: "66 - JRadio Program", videoURL: "_d4CU9MveLE"),
            Video(videoTitle: "67 - JRadioButton Final Program", videoURL: "-ptlsT9KsM8"),
            Video(videoTitle: "68 - JComboBox", videoURL: "vd-k2oBMXUI"),
            Video(videoTitle: "69 - Drop Down List Program", videoURL: "XS4-5GmRnp8"),
            Video(videoTitle: "70 - JList", videoURL: "GBlKa8cNROM"),
            Video(videoTitle: "71 - JList Program", videoURL: "aLkkYbHz16E"),
            Video(videoTitle: "72 - Multiple Selection List", videoURL: "9z_8yEv7nIc"),
            Video(videoTitle: "73 - Moving List Items Program", videoURL: "68X8RUxeXeA"),
            Video(videoTitle: "74 - Mouse Events", videoURL: "hsHqhX0s7Rs"),
            Video(videoTitle: "75 - MouseListener Interface", videoURL: "MpIHF4V3zMc"),
            Video(videoTitle: "76 - MouseListener Interface pt.2", videoURL: "sdUJR_DSyBU"),
            Video(videoTitle: "77 - Adapter Classes", videoURL: "UuKNGMCfSkQ"),
            Video(videoTitle: "78 - File Class", videoURL: "7fC9nL3_AQQ"),
            Video(videoTitle: "79 - Creating Files", videoURL: "G0DfmD0KKyc"),
            Video(videoTitle: "80 - Writing to Files", videoURL: "Bws9aQuAcdg"),
            Video(videoTitle: "81 - Reading From Files", videoURL: "3RNYUKxAgmw"),
            Video(videoTitle: "82 - Exception Handling", videoURL: "K_-3OLkXkzY"),
            Video(videoTitle: "83 - FlowLayout", videoURL: "DFQzFJqOSbA"),
            Video(videoTitle: "84 - Drawing Graphics", videoURL: "2l5-5PMUc5Y"),
            Video(videoTitle: "85 - JColorChooser", videoURL: "052U-bWEXrk"),
            Video(videoTitle: "86 - Drawing More Stuff", videoURL: "OWOeE90ET6w"),
            Video(videoTitle: "87 - Series Finale", videoURL: "38UOAo1c_QA")
        ]
    }
    static func fetchAMC10Videos() -> [Video] {
        return [
            Video(videoTitle: "2018 AMC 10A Question 2", videoURL: "W8rNyoTpASU"),
            Video(videoTitle: "2018 AMC 10A Question 3", videoURL: "bShaVKtJ_4Q"),
            Video(videoTitle: "2018 AMC 10A Question 4", videoURL: "IWkJJo4YB80"),
            Video(videoTitle: "2018 AMC 10A Question 5", videoURL: "WuuC8F9TtAI"),
            Video(videoTitle: "2018 AMC 10A Question 6", videoURL: "eJxaOVmZPYc"),
            Video(videoTitle: "2018 AMC 10A Question 7", videoURL: "i1wPiVsyVJg"),
            Video(videoTitle: "2018 AMC 10A Question 8", videoURL: "fCfad5Xl1ew"),
            Video(videoTitle: "2018 AMC 10A Question 9", videoURL: "eDWNkA4jyQA"),
            Video(videoTitle: "2018 AMC 10A Question 10", videoURL: "WWooxp4CIDc"),
            Video(videoTitle: "2018 AMC 10A Question 11", videoURL: "f2P6vJF-zI4"),
            Video(videoTitle: "2018 AMC 10A Question 12", videoURL: "T1EKz0GAgB4"),
            Video(videoTitle: "2018 AMC 10A Question 14", videoURL: "bMO2J27NDrA"),
            Video(videoTitle: "2018 AMC 10A Question 15", videoURL: "5tzPY4YMdTc"),
            Video(videoTitle: "2018 AMC 10A Question 16", videoURL: "KvrJHFRS7ok"),
            Video(videoTitle: "2018 AMC 10A Question 17", videoURL: "yY6EvMavLvY"),
            Video(videoTitle: "2018 AMC 10A Question 19", videoURL: "68bV3u3TPLU"),
            Video(videoTitle: "2018 AMC 10A Question 20", videoURL: "gmopP_VLkDQ"),
            Video(videoTitle: "2018 AMC 10A Question 21", videoURL: "1JL6_OzibMM"),
            Video(videoTitle: "2018 AMC 10A Question 22", videoURL: "THDzWx8IW5g"),
            Video(videoTitle: "2018 AMC 10A Question 23", videoURL: "mh7BZ5RYMsE"),
            Video(videoTitle: "2018 AMC 10A Question 24", videoURL: "wuc0naX8McA"),
            Video(videoTitle: "2018 AMC 10B Question 2", videoURL: "Fi2DAqBJpEU"),
            Video(videoTitle: "2018 AMC 10B Question 3", videoURL: "fUXzWB1urf8"),
            Video(videoTitle: "2018 AMC 10B Question 4", videoURL: "OmFsCm-QVwY"),
            Video(videoTitle: "2018 AMC 10B Question 5", videoURL: "s0Tnvt9LhD0"),
            Video(videoTitle: "2018 AMC 10B Question 7", videoURL: "y2cD2uZLa9A"),
            Video(videoTitle: "2018 AMC 10B Question 8", videoURL: "0XR2vEMZnvY"),
            Video(videoTitle: "2018 AMC 10B Question 12", videoURL: "gnaxSRDaj-0"),
            Video(videoTitle: "2018 AMC 10B Question 13", videoURL: "7vrMLIceWpg"),
            Video(videoTitle: "2018 AMC 10B Question 14", videoURL: "vzP0O790fak"),
            Video(videoTitle: "2018 AMC 10B Question 15", videoURL: "8yctwrjHw3M"),
            Video(videoTitle: "2018 AMC 10B Question 16", videoURL: "MjZs_GMZMUc"),
            Video(videoTitle: "2018 AMC 10B Question 17", videoURL: "_oxE8Jwz5PU"),
            Video(videoTitle: "2018 AMC 10B Question 18", videoURL: "tBfthQ-55xo"),
            Video(videoTitle: "2018 AMC 10B Question 20", videoURL: "aubDsjVFFTc"),
            Video(videoTitle: "2018 AMC 10B Question 21", videoURL: "qlHE_sAXiY8"),
            Video(videoTitle: "2018 AMC 10B Question 22", videoURL: "2FowNArEEBI")
            
        ]
    }
    static func fetchAMC12Videos() -> [Video] {
        return [
            Video(videoTitle: "Introduction", videoURL: "Mqv35iq8VOk"),
            Video(videoTitle: "AOPS: 2018 AMC 12 A #21", videoURL: "HST5pSPIvZE"),
            Video(videoTitle: "AOPS: 2018 AMC 12 A #22", videoURL: "YTuYzjjg7gw"),
            Video(videoTitle: "AOPS: 2018 AMC 12 A #23", videoURL: "9_j5DKUUBec"),
            Video(videoTitle: "AOPS: 2018 AMC 12 A #24", videoURL: "7J-a1hx9f1I"),
            Video(videoTitle: "AOPS: 2018 AMC 12 A #25", videoURL: "fkgac2KnSB8"),
            Video(videoTitle: "AOPS: 2017 AMC 12 A #21", videoURL: "hSYSNBVPLhE"),
            Video(videoTitle: "AOPS: 2017 AMC 12 A #22", videoURL: "ixDXFRffUZ4"),
            Video(videoTitle: "AOPS: 2017 AMC 12 A #23", videoURL: "MBIiz0mroqk"),
            Video(videoTitle: "AOPS: 2017 AMC 12 A #24", videoURL: "JdERP0d0W64"),
            Video(videoTitle: "AOPS: 2017 AMC 12 A #25", videoURL: "CfO4zIeYrSY"),
            Video(videoTitle: "AOPS: 2016 AMC 12 A #21", videoURL: "hpSyHZwsteM"),
            Video(videoTitle: "AOPS: 2016 AMC 12 A #22", videoURL: "ja1KZ8tVwI8"),
            Video(videoTitle: "AOPS: 2016 AMC 12 A #23", videoURL: "FqRsTNB89ps"),
            Video(videoTitle: "AOPS: 2016 AMC 12 A #24", videoURL: "OkI1HDEj2B8"),
            Video(videoTitle: "AOPS: 2016 AMC 12 A #25", videoURL: "xVKNTQ9bKcg"),
            Video(videoTitle: "AOPS: 2013 AMC 12 A #21", videoURL: "QXDrSRkf96s"),
            Video(videoTitle: "AOPS: 2013 AMC 12 A #22", videoURL: "Hi_Ts09hxUg"),
            Video(videoTitle: "AOPS: 2013 AMC 12 A #23", videoURL: "UI-cdfRbZtI"),
            Video(videoTitle: "AOPS: 2013 AMC 12 A #24", videoURL: "FiB6dLQFJCg"),
            Video(videoTitle: "AOPS: 2013 AMC 12 A #25", videoURL: "pGIFwVH1sxY"),
            Video(videoTitle: "AOPS: 2012 AMC 12 A #21", videoURL: "zLOkISzqeSs"),
            Video(videoTitle: "AOPS: 2012 AMC 12 A #22", videoURL: "UoDO4UFlTy8"),
            Video(videoTitle: "AOPS: 2012 AMC 12 A #23", videoURL: "fm36K88S0LU"),
            Video(videoTitle: "AOPS: 2012 AMC 12 A #24", videoURL: "FiUZTlzA7lg"),
            Video(videoTitle: "AOPS: 2012 AMC 12 A #25", videoURL: "uGbwCJPYNVY"),
            Video(videoTitle: "AOPS: 2012 AMC 12 B #21", videoURL: "lcSKOl-p_gY"),
            Video(videoTitle: "AOPS: 2012 AMC 12 B #22", videoURL: "SE3hYHHYqhk"),
            Video(videoTitle: "AOPS: 2012 AMC 12 B #23", videoURL: "9ytTJr6ctwY"),
            Video(videoTitle: "AOPS: 2012 AMC 12 B #24", videoURL: "KfGrtTOSxZk"),
            Video(videoTitle: "AOPS: 2012 AMC 12 B #25", videoURL: "rJ3JzetSgwc")
            
        ]
    }
    static func fetchAlgorithmVideos() -> [Video] {
        return [
            Video(videoTitle: "1 - Intro, Robert Sedgewick & Kevin Wayne", videoURL: "1QZDe28peZk"),
            Video(videoTitle: "2 - Intro to Graphs", videoURL: "flhgfYu8DFo"),
            Video(videoTitle: "3 - Graph API", videoURL: "NnBk8inSgqY"),
            Video(videoTitle: "4 - Depth First Search", videoURL: "Uj6lQWBU6jk"),
            Video(videoTitle: "5 - Breadth First Search", videoURL: "2dFFKJM0j1E"),
            Video(videoTitle: "6 - Connected Components", videoURL: "BYIz7jJ-VA4"),
            Video(videoTitle: "7 - Graph Challenges", videoURL: "OD2-Ovpx6tc"),
            Video(videoTitle: "8 - Intro to Digraphs", videoURL: "S1xKaQIxMRo"),
            Video(videoTitle: "9 - Digraph API", videoURL: "t6Gr8H2DvMI"),
            Video(videoTitle: "10 - PRG Security Definitions", videoURL: "fCUK6TjBAx0"),
            Video(videoTitle: "11 - Semantic Security", videoURL: "eomGldrNr88"),
            Video(videoTitle: "12 - Stream Ciphers are Semantically Secure", videoURL: "f6Dt_0m-nbI"),
            Video(videoTitle: "13 - What are Block Ciphers?", videoURL: "a28mKx9K8H4"),
            Video(videoTitle: "14 - The Data Encryption Standard", videoURL: "fcjadxYY9G0"),
            Video(videoTitle: "15 - Exhaustive Search Attacks", videoURL: "wtpxNsKCS20"),
            Video(videoTitle: "16 - More Attacks on Block Ciphers", videoURL: "XEu333sBKTY"),
            Video(videoTitle: "17 - The AES Block Cipher", videoURL: "XKCiVdOEvmU"),
            Video(videoTitle: "18 - Block Ciphers From PRGs", videoURL: "1Vtq7IQcHYQ"),
            Video(videoTitle: "19 - Review PRPs and PRFs", videoURL: "YchrmlHUWz8"),
            Video(videoTitle: "20 - Modes of Operation one time Key", videoURL: "OnBNYGGPK_Y"),
            Video(videoTitle: "21 - Security For Many Time Key", videoURL: "si4dM6TR_MU"),
            Video(videoTitle: "22 - Modes of Operation Many Time Key CBC", videoURL: "gbNkAiLYOBE"),
            Video(videoTitle: "23 - Modes of Operation Many Time Key CTR", videoURL: "9i8UL6lXqpg"),
            Video(videoTitle: "24 - Message Authentication Codes", videoURL: "VJMCbMQCrhI"),
            Video(videoTitle: "25 - MACs Based on PRFs", videoURL: "rnA9ar3CDVY"),
            Video(videoTitle: "26 - CBC MAC and NMAC", videoURL: "8ykCKHGf400"),
            Video(videoTitle: "27 - MAC Padding", videoURL: "_ufVwtIuvUY"),
            Video(videoTitle: "28 - PMAC and the Carter Wegman MAC", videoURL: "kYJtrW_MSfU"),
            Video(videoTitle: "29 - Intro to Collision Resistance", videoURL: "0j2Kam7QFWc"),
            Video(videoTitle: "30 - Generic Birthday Attack", videoURL: "XtJTCgD1ohg"),
            Video(videoTitle: "31 - The Merkle Damgard Paradigm", videoURL: "s9S6XRUmpLY"),
            Video(videoTitle: "32 - Constructing Compression Functions", videoURL: "CapbYFNxngE"),
            Video(videoTitle: "33 - HMAC", videoURL: "3KFYCg7qWfU"),
            Video(videoTitle: "34 - Timing attacks on MAC verification", videoURL: "b9eobfui-aQ"),
            Video(videoTitle: "35 - Active attacks on CPA secure encryption", videoURL: "lXyiK4hhH-Q"),
            Video(videoTitle: "36 - Definitions", videoURL: "Zh_b6guQiJg"),
            Video(videoTitle: "37 - Chosen ciphertext attacks", videoURL: "AOPUVd-P13U"),
            Video(videoTitle: "38 - Constructions from Ciphers & MACs", videoURL: "i4AdQDizWCI"),
            Video(videoTitle: "39 - Case Study TLS", videoURL: "BpzOlq1jgks"),
            Video(videoTitle: "40 - CBC Padding Attacks", videoURL: "3bL18vY-3Vs"),
            Video(videoTitle: "41 - Attacking non atomic decryption", videoURL: "a26LVpJgljA"),
            Video(videoTitle: "42 - Key Derivation", videoURL: "iic8FbKuvFg"),
            Video(videoTitle: "43 - Deterministic Encryption", videoURL: "likE6YD9w7Y"),
            Video(videoTitle: "44 - Deterministic EncryptionSIV and Wide PRP", videoURL: "bpC_k_xcTH8"),
            Video(videoTitle: "45 - Tweakable Encryption", videoURL: "-VUGVLgbFLs"),
            Video(videoTitle: "46 - Format Preserving Encryption", videoURL: "LjacONQMO1s"),
            Video(videoTitle: "47 - Trusted 3rd Parties", videoURL: "1x4BUIDvPHo"),
            Video(videoTitle: "48 - Merkle Puzzles", videoURL: "UmwqAx1i_GE"),
            Video(videoTitle: "49 - The Diffie Hellman Protocol", videoURL: "QHw9RVYuBTo"),
            Video(videoTitle: "50 - Public Key Encryption", videoURL: "aoMQlVFkIyc"),
            Video(videoTitle: "51 - Notation", videoURL: "O3OBgvhfuxI"),
            Video(videoTitle: "52 - Fermat & Euler", videoURL: "tleD818mneU"),
            Video(videoTitle: "53 - Modular Eth Roots", videoURL: "vVsHlc71lsg"),
            Video(videoTitle: "54 - Arithmetic Algorithms", videoURL: "XIvyvzAGoJc"),
            Video(videoTitle: "55 - Intractable Problems", videoURL: "zHnMIafV9mc"),
            Video(videoTitle: "56 - Definitions & Security", videoURL: "Y3mut4WlHFE"),
            Video(videoTitle: "57 - Constructions", videoURL: "xSPQrPZ2G9w"),
            Video(videoTitle: "58 - The RSA Trapdoor Functions", videoURL: "ssYa7XH2Kjc"),
            Video(videoTitle: "59 - PKCS 1", videoURL: "F-sfHYG9ZO0"),
            Video(videoTitle: "60 - Is RSA a one way function?", videoURL: "sT04_eUMAbs"),
            Video(videoTitle: "61 - RSA in Practice", videoURL: "Art8WQpIXZk"),
            Video(videoTitle: "62 - The EIGamal Public Key System", videoURL: "bnZ2D43uCcs"),
            Video(videoTitle: "63 - EIGamal Security", videoURL: "ZNNGsHjrG9M"),
            Video(videoTitle: "64 - EIGamal Variants With Better Security", videoURL: "Ko4alB9Cnc8"),
            Video(videoTitle: "65 - A Unifying Theme", videoURL: "hyB-2ANTdvk"),
            Video(videoTitle: "66 - Farewell for now", videoURL: "nUwpSGgNRCM")
        ]
    }
    static func fetchPythonVideos() -> [Video] {
        return [
            Video(videoTitle: "Python Course Intro!", videoURL: "TfnUPK2fdwY"),
            Video(videoTitle: "Python & Pycharm Download", videoURL: "baBBJ7zuAVY"),
            Video(videoTitle: "Strings & Print", videoURL: "YE7cR4_Z9DU"),
            Video(videoTitle: "Math Operations & Int.", videoURL: "okEE7DRexKQ"),
            Video(videoTitle: "Variables", videoURL: "8pRxo0u7X0A"),
            Video(videoTitle: "While Loops", videoURL: "SDPiQ8xnV0w"),
            Video(videoTitle: "For Loops", videoURL: "O77gQTRvZV0"),
            Video(videoTitle: "If-Statements", videoURL: "TRZ-M27-D7Y"),
            Video(videoTitle: "Else & Elif Statements", videoURL: "c1EXAdsxVSU"),
            Video(videoTitle: "Functions", videoURL: "WMmGgtYdBU"),
            Video(videoTitle: "Function Parameters", videoURL: "M3UPtXWTqNU"),
            Video(videoTitle: "Local & Global Variables", videoURL: "hCvi8RZDQA4"),
            Video(videoTitle: "User Input!", videoURL: "cKzW3QLKIuo"),
            Video(videoTitle: "Dictionaries", videoURL: "ZQ0TNeIref8"),
            Video(videoTitle: "Appending & Writing to Files", videoURL: "yfTVGRqMVMo"),
            Video(videoTitle: "Reading to Files", videoURL: "URZpX3iESjU"),
            Video(videoTitle: "Classes", videoURL: "FKJ1HWcYqE4"),
            Video(videoTitle: "Import & Statistics", videoURL: "9x8gLsYJWyE"),
            Video(videoTitle: "Modules", videoURL: "8mPqIWaBhNM"),
            Video(videoTitle: "Lists & Tuples", videoURL: "mYpto0phPN0"),
            Video(videoTitle: "Sets", videoURL: "Oh2W1r-8qYY"),
            Video(videoTitle: "Error Handling", videoURL: "CVZSIR5p5oU"),
            Video(videoTitle: "Make Your Own Program! (Pt. 1)", videoURL: "QkiwPrVIvfo"),
            Video(videoTitle: "Make Your Own Program! (Pt. 2)", videoURL: "3wBzCP5VURI")
        ]
    }
    static func fetchNLPVideos() -> [Video] {
        return [
            Video(videoTitle: "Intro to NLP", videoURL: "n25JjoixM3I"),
            Video(videoTitle: "1 - Examples of Text", videoURL: "NT40U8zU1bg"),
            Video(videoTitle: "2 - Funny Sentences!", videoURL: "UeiUiCRchiU"),
            Video(videoTitle: "3 - Administrative", videoURL: "rIRI3pTj-uc"),
            Video(videoTitle: "4 - Why NLP is Hard", videoURL: "NHtohvD7gxY"),
            Video(videoTitle: "5 - Background", videoURL: "0X-n4Z1U9wI"),
            Video(videoTitle: "6 - Linguistics", videoURL: "lgijqrsE4jw"),
            Video(videoTitle: "7 - Text Similarity", videoURL: "GDso6md3DBw"),
            Video(videoTitle: "8 - Parts of Speech", videoURL: "BYdtJs6wU5o"),
            Video(videoTitle: "9 - Morphology and the Lexicon", videoURL: "CzMDw-hH7B0"),
            Video(videoTitle: "10 - Morphological Similarity", videoURL: "hdwhI3VYO5A"),
            Video(videoTitle: "11 - Spelling Similarity", videoURL: "1KySp2fTuag"),
            Video(videoTitle: "12 - NACLO", videoURL: "Dm3GswBjgog"),
            Video(videoTitle: "13 - Preprocessing", videoURL: "0xgH2WCRGww"),
            Video(videoTitle: "14 - Semantic Similarity", videoURL: "PxgkddPbjrM"),
            Video(videoTitle: "15 - Thesaurus-based Word Similarity", videoURL: "eM62rKR1TlE"),
            Video(videoTitle: "16 - Vector Space Model", videoURL: "TjIrEYWlonE"),
            Video(videoTitle: "17 - Dimensionality Reduction", videoURL: "dk02ajKGGfg"),
            Video(videoTitle: "18 - NLP Tasks", videoURL: "ygPzxsPzy6s"),
            Video(videoTitle: "19 - NLP Tasks 2/3", videoURL: "encEbxnJ3j4"),
            Video(videoTitle: "20 - NLP Tasks 3/3", videoURL: "_Vcu034k2Zk"),
            Video(videoTitle: "21 - Syntax", videoURL: "8AUzaxLURpI"),
            Video(videoTitle: "22 - Parsing", videoURL: "g8E3tkdfLC8"),
            Video(videoTitle: "23 - Classic Parsing Methods", videoURL: "34HEz8miVQA"),
            Video(videoTitle: "24 - Earley Parser", videoURL: "Nm7-ZEnW3b0"),
            Video(videoTitle: "25 - The Penn Treebank", videoURL: "NUV6vXK8FCc"),
            Video(videoTitle: "26 - Parsing noun sequences", videoURL: "qGYno3fqbm4"),
            Video(videoTitle: "27 - PPA (1/3)", videoURL: "bZ2RT_O6AtY"),
            Video(videoTitle: "28 - PPA (2/3)", videoURL: "XDkN1BfiNB4"),
            Video(videoTitle: "29 - PPA (3/3)", videoURL: "2baHDVfRyM4"),
            Video(videoTitle: "30 - Statistical Parsing", videoURL: "hgaeB2JloJY"),
            Video(videoTitle: "31 - Lexicalized Parsing", videoURL: "aBkH9gyz2IQ"),
            Video(videoTitle: "32 - Dependency Parsing ", videoURL: "6ptMYdeq2Sg"),
            Video(videoTitle: "33 - Alternative Parsing Formalisms", videoURL: "g7oaLX3Tu9c"),
            Video(videoTitle: "34 - Probabilities", videoURL: "g8rNRwalUps"),
            Video(videoTitle: "35 - Bayes Theorem", videoURL: "16KCrsiFn34"),
            Video(videoTitle: "36 - Language Modeling (1/3) ", videoURL: "0NJLn9DKT3U"),
            Video(videoTitle: "37 - Language Modeling (1/3 cont'd )", videoURL: "N7Svyhgzq6s"),
            Video(videoTitle: "38 - Language Modeling (2/3)", videoURL: "XDbU1wF2yzs"),
            Video(videoTitle: "39 - Language Modeling (3/3)", videoURL: "6RFTFnsBRUU"),
            Video(videoTitle: "40 - Word Sense", videoURL: "m3a19HrzBMc"),
            Video(videoTitle: "41 - Noisy Channel Model", videoURL: "X6E35hNvkpI"),
            Video(videoTitle: "42 - Part of Speech Tagging", videoURL: "GJgEBhYqs7U"),
            Video(videoTitle: "43 - Hidden Markov Models (1/2)", videoURL: "HVAwc0SOEoQ"),
            Video(videoTitle: "44 - Hidden Markov Models (2/2)", videoURL: "w0tpuVuQoPg"),
            Video(videoTitle: "45 - Statistical POS Tagging", videoURL: "X6rDshsjW_0"),
            Video(videoTitle: "46 - Information Extraction", videoURL: "X6rDshsjW_0"),
            Video(videoTitle: "47 - Relation Extraction", videoURL: "TbrlRei_0h8"),
            Video(videoTitle: "48 - Question Answering", videoURL: "Q4jIWYYGCpw"),
            Video(videoTitle: "49 - Evaluation of QA", videoURL: "77-5S6vB_PY"),
            Video(videoTitle: "50 - System Architecture (QA)", videoURL: "u2bl-5GhomA"),
            Video(videoTitle: "51 - Question Answering Systems (1/2)", videoURL: "Kzi6tE4JaGo"),
            Video(videoTitle: "52 - Question Answering Systems (2/2)", videoURL: "AdU4iNVgnOU"),
            Video(videoTitle: "53 - Summarization", videoURL: "02Qvjff8Q_I"),
            Video(videoTitle: "54 - Summarization Techniques (1/3)", videoURL: "N5N-HCUE3G4"),
            Video(videoTitle: "55 - Summarization Techniques (2/3)", videoURL: "cz8UImIopnQ"),
            Video(videoTitle: "56 - Summarization Techniques (3/3)", videoURL: "AgvfJddkzvE"),
            Video(videoTitle: "57 - Summarization Evaluation", videoURL: "FGQg7qCo7RE"),
            Video(videoTitle: "58 - Sentence Simplification", videoURL: "0X4zlwXujco"),
            Video(videoTitle: "59 - Collocations", videoURL: "Kf25kCKuOUI"),
            Video(videoTitle: "60 - Information Retrieval", videoURL: "QRtHveTuKNs"),
            Video(videoTitle: "61 - Evaluation of IR", videoURL: "kWDyEICkn5E"),
            Video(videoTitle: "62 - Text Classification ", videoURL: "BvSrkGhJHYk"),
            Video(videoTitle: "63 - Text Clustering", videoURL: "WY5MdnhoG9w"),
            Video(videoTitle: "64 - Information Retrieval Toolkits", videoURL: "6t73liRMWd0"),
            Video(videoTitle: "65 - Sentiment Analysis", videoURL: "8msdx6nLhFk"),
            Video(videoTitle: "66 - Sentiment Lexicons", videoURL: "qnWri5_tEog"),
            Video(videoTitle: "67 - Semantics", videoURL: "OTg4_VKze6g"),
            Video(videoTitle: "68 - Represent & Understand Meaning", videoURL: "dmhyc8lVPFM"),
            Video(videoTitle: "69 - First Order Logic", videoURL: "s7OMfvbg3gY"),
            Video(videoTitle: "70 - Knowledge Representation", videoURL: "gCnfnZYVNuM"),
            Video(videoTitle: "71 - Inference", videoURL: "ro5BFH1Ro4Q"),
            Video(videoTitle: "72 - Semantic Parsing", videoURL: "Uj4TMHiUi8I"),
            Video(videoTitle: "73 - Discourse Analysis", videoURL: "6yGRaHSnelI"),
            Video(videoTitle: "74 - Coherence", videoURL: "cwm-mlXwvsY"),
            Video(videoTitle: "75 - Dialogue Systems", videoURL: "1c_0Ly7tUxY"),
            Video(videoTitle: "76 - Machine Translation", videoURL: "K2kLC7hSucE"),
            Video(videoTitle: "77 - MT Basic Techniques", videoURL: "rpsDMgJPons"),
            Video(videoTitle: "78 - MT Noisy Channel Methods", videoURL: "JUW2jFiuK6I"),
            Video(videoTitle: "79 - MT Advanced Methods", videoURL: "owSClMuxQTY"),
            Video(videoTitle: "80 - Text Generation", videoURL: "3BqCZ2Fxylw"),
            Video(videoTitle: "81 - Coherence", videoURL: "cwm-mlXwvsY"),
            
        ]
    }
    static func fetchCVideos() -> [Video] {
        return [
            Video(videoTitle: "1 - C++ Introduction", videoURL: "tvC1WCdV1XU"),
            Video(videoTitle: "2 - Simple C++ program", videoURL: "SWZfFNyUsxc"),
            Video(videoTitle: "3 - More on Printing Text", videoURL: "sPv0HQ8xOaU"),
            Video(videoTitle: "4 - Variables", videoURL: "QwBSv4-_Lmk"),
            Video(videoTitle: "5 - Creating a simple calculator", videoURL: "yjucJUsHSqg"),
            Video(videoTitle: "6 - Variables memory concepts", videoURL: "3Iq_uFbc4L4"),
            Video(videoTitle: "7 - Basic Arithmetic", videoURL: "L1z2dpCosXU"),
            Video(videoTitle: "8 - If Statements", videoURL: "yEY8xlnarNo"),
            Video(videoTitle: "9 - Functions", videoURL: "bsWWHo4KDHE"),
            Video(videoTitle: "10 - Functions w/ Parameters", videoURL: "-87KQS-rZCA"),
            Video(videoTitle: "11 - Multiple Parameters!", videoURL: "fQ_CBGVfGbM"),
            Video(videoTitle: "12 - Classes & Objects", videoURL: "ABRP_5RYhqU"),
            Video(videoTitle: "13 - Using Variables in Classes", videoURL: "jTS7JTud1qQ"),
            Video(videoTitle: "14 - Constructors", videoURL: "_b7odUc7lg0"),
            Video(videoTitle: "15 - Separate Classes", videoURL: "NTip15BHVZc"),
            Video(videoTitle: "16 - If statements.. again?", videoURL: "uYciTJ7CDOY"),
            Video(videoTitle: "17 - If/Else Statements", videoURL: "jK83lln_T1k"),
            Video(videoTitle: "18 - While Loops", videoURL: "KLKhsaOPnLk"),
            Video(videoTitle: "19 - A Program w/ Loops", videoURL: "GGA0z_6tvOU"),
            Video(videoTitle: "20 - Sentinel Controlled Program", videoURL: "791XRPJYdfA"),
            Video(videoTitle: "21 - Assignment & Increment", videoURL: "T0kEDZ-tuNw&"),
            Video(videoTitle: "22 - Now... For Loops", videoURL: "sBO8yvyyBI0"),
            Video(videoTitle: "23 - Stock Market Simulator!", videoURL: "1S__GRWtyvg"),
            Video(videoTitle: "24 - The DO while loop?", videoURL: "yRdPe2acogw"),
            Video(videoTitle: "25 - Switch Statements", videoURL: "TNUCZpgPjrw"),
            Video(videoTitle: "26 - Logical Operators", videoURL: "o78khWdmqIE"),
            Video(videoTitle: "27 - Random Number Generator??", videoURL: "naXUIEAIt4U"),
            Video(videoTitle: "28 - Default Args. & Params", videoURL: "66zF2rqoKI8"),
            Video(videoTitle: "29 - Unary Scope Resolution", videoURL: "ZwxMlIS6TLM"),
            Video(videoTitle: "30 - Function Overloading", videoURL: "IAMzWp3kS_k"),
            Video(videoTitle: "31 - Recursion", videoURL: "4agL-MQq05E"),
            Video(videoTitle: "32 - Arrays!!", videoURL: "1kLw8kZuccQ"),
            Video(videoTitle: "33 - Array Using Loops...", videoURL: "Z9Wc8EsGjJY"),
            Video(videoTitle: "34 - Using Arrays in Calculations", videoURL: "v2dKtxtWT5o"),
            Video(videoTitle: "35 - Passing Arrays in Functions", videoURL: "VnZbghMhfOY"),
            Video(videoTitle: "36 - Multidimensional Arrays 😅", videoURL: "B3iC40frU4M"),
            Video(videoTitle: "37 - Print multidimensional arrays", videoURL: "pAKZp_EucVg"),
            Video(videoTitle: "38 - Intro to Pointers", videoURL: "Fa6S8Pz924k"),
            Video(videoTitle: "39 - Pass by Reference w/ Pointers", videoURL: "_ja8iizm7nk"),
            Video(videoTitle: "40 - Sizeof Function", videoURL: "_5EEHKkvv1s"),
            Video(videoTitle: "41 - Pointers & Math", videoURL: "dPAbm-3iAN4"),
            Video(videoTitle: "42 - Arrow Member Selection", videoURL: "2RP4f9beidc"),
            Video(videoTitle: "43 - Deconstructors", videoURL: "4P4Im0vF_mU"),
            Video(videoTitle: "44 - Const. Objects", videoURL: "k55CRqm1gzk"),
            Video(videoTitle: "45 - Member Initializers", videoURL: "53VYYMy-LBo"),
            Video(videoTitle: "46 - Compositions pt.1", videoURL: "jn3lT07owCo"),
            Video(videoTitle: "47 - Compositions pt.2", videoURL: "jCaxfmcDYjs"),
            Video(videoTitle: "48 - Class friends!!", videoURL: "WCFGNdXSzus"),
            Video(videoTitle: "49 - The \"this\" Keyword", videoURL: "Fcdkcx4achs"),
            Video(videoTitle: "50 - Operator Overloading", videoURL: "PgGhEovFhd0"),
            Video(videoTitle: "51 - MORE Operator Overloading", videoURL: "q4vZIF-uMzs"),
            Video(videoTitle: "52 - Inheritance", videoURL: "gq2Igdc-OSI"),
            Video(videoTitle: "53 - Protected Members", videoURL: "DHAAy4GJ684"),
            Video(videoTitle: "54 - Derived Class Constructors", videoURL: "Z_vJEKU9WTg"),
            Video(videoTitle: "55 - Intro to Polymorphism", videoURL: "R_PPA9eejDw"),
            Video(videoTitle: "56 - Virtual Functions", videoURL: "DudHooleNVg"),
            Video(videoTitle: "57 - Abstract Classes & Virtual Func.", videoURL: "ndz3EHpFEZc"),
            Video(videoTitle: "58 - Function Templates", videoURL: "W0aoAm6eYSk"),
            Video(videoTitle: "59 - Now w/ Multiple Parameters", videoURL: "SeleR7PDs5Q"),
            Video(videoTitle: "60 - Class Templates", videoURL: "U2QvTsMvWmM"),
            Video(videoTitle: "61 - Template Specializations", videoURL: "8kjVFp-Y4GA"),
            Video(videoTitle: "62 - Exception Handling", videoURL: "mFAaqmj399I"),
            Video(videoTitle: "63 - MORE Exception Handling", videoURL: "5369xtKS42s"),
            Video(videoTitle: "64 - Working w/ Files", videoURL: "HcONWqVyvlg"),
            Video(videoTitle: "65 - File Handling Tips", videoURL: "qdkabVYgV24"),
            Video(videoTitle: "66 - Write Custom File Structs.", videoURL: "iGWhPwh3n-o"),
            Video(videoTitle: "67 - Read Custom File Structs.", videoURL: "EjJY7yA5SWw"),
            Video(videoTitle: "68 - Cool Program w/ Files!", videoURL: "Xb-ae2NEGRs"),
            Video(videoTitle: "69 - Finish the Program!", videoURL: "xpV-Dpflob8"),
            Video(videoTitle: "70 - Final Program: The Review", videoURL: "86rBqzYIbjA"),
            Video(videoTitle: "71 - String Class & Functions", videoURL: "dSfjBoip4c0"),
            Video(videoTitle: "72 - More String Functions", videoURL: "nkKeA74p3RY"),
            Video(videoTitle: "73 - Final Video for this Series!", videoURL: "Djc4AScpuf4"),
            Video(videoTitle: "74 - A message from Andrew!", videoURL: "kx6aJahE9dg")
        ]
    }
    static func fetchSwiftBVideos() -> [Video] {
        return [
            Video(videoTitle: "1 - Swift Variables", videoURL: "2OZ07fklur8"),
            Video(videoTitle: "2 - Different Data Types", videoURL: "BlXrMgmvNBI"),
            Video(videoTitle: "3 - If Statements", videoURL: "z_4JuCD0mz8"),
            Video(videoTitle: "4 - Switch Statements", videoURL: "PZEWRDbSn6c"),
            Video(videoTitle: "5 - The Swift Loop", videoURL: "vxyrLbmm9Oo"),
            Video(videoTitle: "6 - The Swift Loop pt.2", videoURL: "XDJXLw0Y3Hs"),
            Video(videoTitle: "7 - Functions", videoURL: "2kwyQ5w00Uc"),
            Video(videoTitle: "8 - Functions pt.2", videoURL: "jNiBS0bxVQQ"),
            Video(videoTitle: "9 - Classes pt.1", videoURL: "ZDzdz52tex4"),
            Video(videoTitle: "10 - Classes pt.2: Inheritance", videoURL: "CnvlxNC6FlQ"),
            Video(videoTitle: "11 - UIKit", videoURL: "tHjMdmFlGBo"),
            Video(videoTitle: "12 - Initializers", videoURL: "6GvxKCGcZC4"),
            Video(videoTitle: "13 - What are Optionals??", videoURL: "uT2IHQpE3ms"),
            Video(videoTitle: "14 - Properties...", videoURL: "kmET5JcKcx8"),
            Video(videoTitle: "15 - Initializers... again?", videoURL: "LUlQTmf1Iek"),
            Video(videoTitle: "16 - Arrays", videoURL: "RFYDvYXsrxQ"),
            Video(videoTitle: "17 - Dictionaries", videoURL: "7srt4mMA3Qw"),
            Video(videoTitle: "18 - Can you do these challenges?", videoURL: "U4hGXWKfYy0"),
            Video(videoTitle: "19 - Challenge Solutions", videoURL: "wpRlKzNS5Y4")
            
        ]
    }
    static func fetchMLVideos() -> [Video] {
        return [
            Video(videoTitle: "1 - Welcome!", videoURL: "eiNFub2yags"),
            Video(videoTitle: "2 - Language Types & Examples", videoURL: "5Gsto8UWWCg"),
            Video(videoTitle: "3 - Machine Learning v. Statistical Modeling", videoURL: "jaI5aheBOi0"),
            Video(videoTitle: "4 - Supervised v. Unsupervised", videoURL: "cfj6yaYE86U"),
            Video(videoTitle: "5 - Supervised Classification", videoURL: "Lf2bCQIktTo"),
            Video(videoTitle: "6 - Unsupervised Classification", videoURL: "BodFg6GR06E"),
            Video(videoTitle: "7 - K Nearest Neighbors", videoURL: "ZBHStob8lhc"),
            Video(videoTitle: "8 - Decision Trees", videoURL: "HDvSevhTgDM"),
            Video(videoTitle: "9 - Random Forests", videoURL: "BEfnJkL_LwI"),
            Video(videoTitle: "10 - Random Forest Reliability", videoURL: "Wra3LJVDtpE"),
            Video(videoTitle: "11 - Decision Trees Pros & Cons", videoURL: "JUUNQG4SXG4"),
            Video(videoTitle: "12 - Regression Algorithms", videoURL: "uY0KBz6hMFo"),
            Video(videoTitle: "13 - Model Evaluation", videoURL: "VcSNDMBTE-s"),
            Video(videoTitle: "14 - Overfitting & Underfitting", videoURL: "hI8YJDpCxf0"),
            Video(videoTitle: "15 - Different Evaluation Models", videoURL: "-NwJyTuMe-8"),
            Video(videoTitle: "16 - K Means Clustering", videoURL: "77psYm8bLsQ"),
            Video(videoTitle: "17 - Hierarchical Clustering Pros & Cons", videoURL: "R8cwXFth9M0"),
            Video(videoTitle: "18 - Distance Between Clusters", videoURL: "O4J2aq4yQbI"),
            Video(videoTitle: "19 - Hierarchical Clustering", videoURL: "tA1WyStMAlU"),
            Video(videoTitle: "20 - Density Based Clustering", videoURL: "sJQHz97sCZ0"),
            Video(videoTitle: "21 - Dimensionality Reduction", videoURL: "AU_hBML2H1c"),
            Video(videoTitle: "22 - Collaborative Filtering", videoURL: "wTZUHiLUY94"),
            Video(videoTitle: "Course Summary", videoURL: "p6F7cJrXocw")
        ]
    }
    static func fetchDLVideos() -> [Video] {
        return [
            Video(videoTitle: "Welcome to Deep Learning!", videoURL: "MrijcdNl_U4"),
            Video(videoTitle: "1 - Intro to TensorFlow", videoURL: "MotG3XI2qSs"),
            Video(videoTitle: "2 - TensorFlow's Library", videoURL: "RFZaaUFxBzc"),
            Video(videoTitle: "3 - Tensors, Variables, Placeholders", videoURL: "zgV-WzLyrYE"),
            Video(videoTitle: "4 - Linear Regression", videoURL: "zNalsMIB3NE"),
            Video(videoTitle: "5 - Logistic Regression", videoURL: "4cBRxZavvTo"),
            Video(videoTitle: "6 - Activation Functions", videoURL: "FXwKlBXNXdg"),
            Video(videoTitle: "7 - Convolution Networks", videoURL: "SSoY8uQwDW4"),
            Video(videoTitle: "8 - Convolution & Feature Learning", videoURL: "k8GgdLdWF80"),
            Video(videoTitle: "9 - Convolution w/ Python & TF", videoURL: "UJCJSVZG-Vo"),
            Video(videoTitle: "10 - The MNIST Database", videoURL: "e7zzXYy4Pz4"),
            Video(videoTitle: "11 - Multilayer Perceptron", videoURL: "kDHR7MjZyTQ"),
            Video(videoTitle: "12 - Convolution Network w/ TF", videoURL: "yL-MkBSv18c"),
            Video(videoTitle: "13 - The Sequential Problem", videoURL: "z9p397QMZdU"),
            Video(videoTitle: "14 - The RNN Model", videoURL: "C0xoB8L8ms0"),
            Video(videoTitle: "15 - Long Short Term Memory", videoURL: "xPotjBiIFFA"),
            Video(videoTitle: "16 - Recursive Neural Tensor", videoURL: "Z56jojdmDV0"),
            Video(videoTitle: "17 - Language Modelling", videoURL: "vZqB3rbTQEE"),
            Video(videoTitle: "18 - Unsupervised Learning", videoURL: "edM0_C4j6R0"),
            Video(videoTitle: "19 - RBMs & Autoencoders", videoURL: "FsAvo0E5Pmw"),
            Video(videoTitle: "20 - Initializing a RBM", videoURL: "BflmfXpin58"),
            Video(videoTitle: "21 - Training a RBM", videoURL: "jlwUqksvnRs"),
            Video(videoTitle: "22 - Reccomendation System w/ RBM", videoURL: "8EaVZbmAnV0"),
            Video(videoTitle: "23 - Intro to Autoencoders", videoURL: "oYfhEmg-i8w"),
            Video(videoTitle: "24 - Autoencoder Structure", videoURL: "H_Bi_PQWJJc"),
            Video(videoTitle: "25 - Autoencoders w/ TensorFlow", videoURL: "HvebaWxtr7s"),
            Video(videoTitle: "26 - Deep Belief Networks", videoURL: "pIaTgr5GEEE"),
            Video(videoTitle: "Conclusion", videoURL: "6ai5-4-uGuM")
        ]
    }
    static func fetchHTMLVideos() -> [Video] {
        return [
            Video(videoTitle: "Course Introduction", videoURL: "yTHTo28hwTQ"),
            Video(videoTitle: "1 - Your First Webpage!", videoURL: "bfqBUDk99Tc"),
            Video(videoTitle: "2 - Find a Code Editor", videoURL: "-8IoQTg5Ybs"),
            Video(videoTitle: "3 - Lists", videoURL: "KHT6scxGm38"),
            Video(videoTitle: "4 - Parent-Child Relation", videoURL: "Pf8xmAZYZC4"),
            Video(videoTitle: "5 - Heading Tags", videoURL: "1JFeWDZ-2D8"),
            Video(videoTitle: "6 - Block Quotes", videoURL: "P7KU6mqdmJ0"),
            Video(videoTitle: "7 - Anchors", videoURL: "xIFZdFeGgoE"),
            Video(videoTitle: "8 - Your First Stylesheet!", videoURL: "o1Vqr1MdRmg"),
            Video(videoTitle: "9 - Clean Proj. Stuctures", videoURL: "g7js1fW4AZw"),
            Video(videoTitle: "10 - Images", videoURL: "xLDZvePzgK8"),
            Video(videoTitle: "11 - Necessity of Divs", videoURL: "28z80vRCHYo"),
            Video(videoTitle: "12 - IDs & Classes", videoURL: "4A2NP5TdDBg"),
            Video(videoTitle: "13 - Your First Assignment!", videoURL: "bEuTfgwb6lU"),
            Video(videoTitle: "14 - Assignment Solutions", videoURL: "yb_xJJXUvyg"),
            Video(videoTitle: "15 - Floats, Simple Layouts", videoURL: "4qEh8bwDW0I"),
            Video(videoTitle: "16 - Navigation", videoURL: "f62FD8t4aPU"),
            Video(videoTitle: "17 - Intro to Forums", videoURL: "4DS4z20ZGyI"),
            Video(videoTitle: "18 - Image Replacement", videoURL: "jnG3mtEhpRQ"),
            Video(videoTitle: "19 - Typography Basics", videoURL: "AKMgc4rzTrc"),
            Video(videoTitle: "20 - Relative & Absolute", videoURL: "6Z8I8sOinUo"),
            Video(videoTitle: "21 - Website Fragment", videoURL: "AqAFnB-z8-Q"),
            Video(videoTitle: "22 - Importance of Validation", videoURL: "VIgxwR9AVrk"),
            Video(videoTitle: "23 - Zen Coding", videoURL: "65QhaSFuxdo"),
            Video(videoTitle: "24 - Resets & Normalizing", videoURL: "IgFfsZfkd24"),
            Video(videoTitle: "25 - CSS Frameworks", videoURL: "tm84gW72KFU"),
            Video(videoTitle: "26 - Final Project Markup!", videoURL: "CilS1-ukeUA"),
            Video(videoTitle: "27 - Slicing a PSD", videoURL: "j4kTLpezHDI"),
            Video(videoTitle: "28 - Creating Snippets", videoURL: "Hr9dv5FCpZw"),
            Video(videoTitle: "29 - CSS for out Website", videoURL: "zvSR_2v5xj8"),
            Video(videoTitle: "30 - Finishing the Site!", videoURL: "I9dNFHasF_U"),
            Video(videoTitle: "Conclusion", videoURL: "cUgpPAP0lUM")
        ]
    }
    static func fetchGameVideos() -> [Video] {
        return [
            Video(videoTitle: "Getting Started!", videoURL: "j48LtUkZRjU"),
            Video(videoTitle: "1 - Unity Basics", videoURL: "IlKaB1etrik"),
            Video(videoTitle: "2 - Start Programming", videoURL: "9ZEu_I-ido4"),
            Video(videoTitle: "3 - Make the Player Move!", videoURL: "Au8oX5pu5u4"),
            Video(videoTitle: "4 - Working w/ the Camera", videoURL: "HVB6UVcb3f8"),
            Video(videoTitle: "5 - Collision Detection", videoURL: "gAB64vfbrhI"),
            Video(videoTitle: "6 - Making the Gameplay", videoURL: "D4I0I3QJAvc"),
            Video(videoTitle: "7 - Score & UI", videoURL: "TAGZxRMloyU"),
            Video(videoTitle: "8 - Create a GAME OVER", videoURL: "VbZ9_C4-Qbo"),
            Video(videoTitle: "9 - Make Winning Levels", videoURL: "Iv7A8TzreY4"),
            Video(videoTitle: "10 - Finishing Our Game", videoURL: "r5NWZoTSjWs")
        ]
    }
    static func fetchAndroidVideos() -> [Video] {
        return [
            Video(videoTitle: "Course Introduction", videoURL: "yTHTo28hwTQ"),
            Video(videoTitle: "1 - Introduction", videoURL: "QAbQgLGKd3Y"),
            Video(videoTitle: "2 - Download Android Studio", videoURL: "zEsDwzjPJ5c"),
            Video(videoTitle: "3 - Project Setup", videoURL: "zEsDwzjPJ5c"),
            Video(videoTitle: "4 - Run a Simple App", videoURL: "qKRWC3Q8wRw"),
            Video(videoTitle: "5 - Tour of the Interface", videoURL: "-pdTqBq2TFQ"),
            Video(videoTitle: "6 - Android Studio Tips", videoURL: "OUCjk_n3raM"),
            Video(videoTitle: "7 - Create a Custom AVD", videoURL: "XWk5hKmgAmE"),
            Video(videoTitle: "8 - Basic App Overview", videoURL: "9l1lfWAiHPg"),
            Video(videoTitle: "9 - Activity States", videoURL: "NMDPxN8FgXM"),
            Video(videoTitle: "10 - Running the State", videoURL: "9LbETUPM_sY"),
            Video(videoTitle: "11 - UI Design", videoURL: "cOYzJN6A-JM"),
            Video(videoTitle: "12 - More About UI", videoURL: "72mf0rmjNAA"),
            Video(videoTitle: "13 - Create an Interface", videoURL: "MdOxtws4DsI"),
            Video(videoTitle: "14 - Properties w/ Widgets", videoURL: "RLDqbEhUjVk"),
            Video(videoTitle: "15 - More Widgets", videoURL: "cXKsFHRG2_c"),
            Video(videoTitle: "16 - Convert dip to px", videoURL: "dJPhexlBOiw"),
            Video(videoTitle: "17 - GirdLayout", videoURL: "4bXOr5Rk1dk"),
            Video(videoTitle: "18 - Event Handling", videoURL: "oB9gpMqv-fg"),
            Video(videoTitle: "19 - Event Listener & Callback", videoURL: "jxoG_Y6dvU8"),
            Video(videoTitle: "20 - Multiple Event Listeners", videoURL: "bBUeH5oNBxI"),
            Video(videoTitle: "21 - Gestures", videoURL: "zsNpiOihNXU"),
            Video(videoTitle: "22 - Running the Gesture App", videoURL: "V_KbEfhf1qc"),
            Video(videoTitle: "23 - Fragments", videoURL: "dQ6uc__qP-g"),
            Video(videoTitle: "24 - Design the Top Fragment", videoURL: "PWAlLiy5p2k"),
            Video(videoTitle: "25 - Create the Fragment Class", videoURL: "yOBQHf5nM2I"),
            Video(videoTitle: "26 - Finishing the Meme 😂🤞", videoURL: "dYy9adsIJDQ"),
            Video(videoTitle: "27 - Listen to Button Clicks", videoURL: "vyykjIPNBXY"),
            Video(videoTitle: "28 - Activity Communication", videoURL: "MHHXxWbSaho"),
            Video(videoTitle: "29 - Change Meme Text", videoURL: "BzCj2-6jZKo"),
            Video(videoTitle: "30 - Dank Meme Bro", videoURL: "sPvCEsGm8us"),
            Video(videoTitle: "31 - Master Detail Flow", videoURL: "jNoLvbD-O6E"),
            Video(videoTitle: "32 - Master Detail Flow Ex.", videoURL: "iNzrUu784dY"),
            Video(videoTitle: "33 - Overflow Menu", videoURL: "iwE1bnRlZw0"),
            Video(videoTitle: "34 - Animations & Transitions", videoURL: "n4IyvL-ACbk"),
            Video(videoTitle: "35 - Intents", videoURL: "06bcsMx-7QQ"),
            Video(videoTitle: "36 - Sned Data in Intents", videoURL: "mPGCLKRCG-8"),
            Video(videoTitle: "37 - Send Broadcast Intents", videoURL: "X69q01TY1ic"),
            Video(videoTitle: "38 - Recieve Broadcast Intents", videoURL: "htU_Rd-DW2U"),
            Video(videoTitle: "39 - Threads", videoURL: "1TiEQ0WhvSU"),
            Video(videoTitle: "41 - Thread Handlers", videoURL: "SCwU-gy3HoM"),
            Video(videoTitle: "41 - Intent Services", videoURL: "-sBxmjrSn34"),
            Video(videoTitle: "42 - Services", videoURL: "9YapLOfQ-dY"),
            Video(videoTitle: "43 - Bound Services", videoURL: "0c4jRCm353c"),
            Video(videoTitle: "44 - Bound Service Ex.", videoURL: "zCj5Qzzex_A"),
            Video(videoTitle: "45 - Listview", videoURL: "U_Jvk4G28YE"),
            Video(videoTitle: "46 - Listview Ex.", videoURL: "A-_hKWMA7mk"),
            Video(videoTitle: "47 - ListView Row", videoURL: "_sStCBdJkQg"),
            Video(videoTitle: "48 - ListView Adapter", videoURL: "nOdSARCVYic"),
            Video(videoTitle: "49 - Save Data w/ SQLite", videoURL: "_vQaOvPsLko"),
            Video(videoTitle: "50 - SQLite Database", videoURL: "q3rhteIierY"),
            Video(videoTitle: "51 - Create a SQLIte Database", videoURL: "Jcmp09LkU-I"),
            Video(videoTitle: "52 - Add & Delete Rows", videoURL: "GAyvtK4cWLA"),
            Video(videoTitle: "53 - Print Database Results", videoURL: "bTWJ8d1hbvw"),
            Video(videoTitle: "54 - Test SQLite App", videoURL: "PrMhjEh2ySk"),
            Video(videoTitle: "55 - Play Videos", videoURL: "oF9yZenJtjI"),
            Video(videoTitle: "56 - Capture Images", videoURL: "my8PSy2DBsY"),
            Video(videoTitle: "57 - Take Photos!", videoURL: "k1Wc0vmD284"),
            Video(videoTitle: "58 - Image Effects", videoURL: "4x_G2j_0IH0"),
            Video(videoTitle: "59 - Inverting Images", videoURL: "bCxTdk4xJpU"),
            Video(videoTitle: "60 - Photo Filters", videoURL: "hR8Uw9cy50U"),
            Video(videoTitle: "61 - Notifications", videoURL: "SWsuijO5NGE"),
            Video(videoTitle: "62 - Custom Notifications", videoURL: "NgQzJ0s0XmM"),
            Video(videoTitle: "63 - Styles", videoURL: "S2V5jlLjwPU"),
            Video(videoTitle: "64 - Themes", videoURL: "3g-HKRJrtnI"),
            Video(videoTitle: "65 - Shared Preferences", videoURL: "hCJkUd7YEXs"),
            Video(videoTitle: "66 - Shared Pref. Example", videoURL: "xv_JJbjDQ3M"),
            Video(videoTitle: "67 - Launcher Icon", videoURL: "vjCrPlEEZBo"),
            Video(videoTitle: "68 - Working with Github", videoURL: "ESNum4uyhEI"),
            Video(videoTitle: "69 - APK File for Distribution", videoURL: "z8QVkvR2Rck"),
            Video(videoTitle: "70 - LibGDX Gave Development", videoURL: "p_hp6vMeewQ"),
            Video(videoTitle: "71 - LibGDX Game Structure", videoURL: "wCjbRq8MPVY"),
            Video(videoTitle: "72 - LibGDX Displaying Text", videoURL: "e2A_9LBxNOg"),
            Video(videoTitle: "73 - LibGDX Image Display", videoURL: "iNzdk29Hrmw"),
            Video(videoTitle: "74 - LibGDX Animation", videoURL: "vjgdX95HVrM"),
            Video(videoTitle: "75 - LibGDX User Input", videoURL: "N9AqGS_Tlnw"),
            Video(videoTitle: "76 - LibGDX Game Camera", videoURL: "6IWhrl--Aa4"),
            Video(videoTitle: "77 - LibGDX Sound Effects", videoURL: "t1YhuHHMFd0")
        ]
    }
    
}
